services:
  filesystem-mcp:
    build:
      context: ./filesystem-mcp
    env_file:
      - ./filesystem-mcp/.env
    ports:
      - "8011:8000"
      - "9000-9100:9000-9100"
    volumes:
      - /home/nbrown:/workspace
    environment:
      - WORKSPACE_ROOT=/workspace

  vision-mcp:
    build:
      context: ./vision-mcp
    env_file:
      - ./vision-mcp/.env
    ports:
      - "8012:8000"

  text-classifier-mcp:
    build:
      context: ./text-classifier-mcp
    env_file:
      - ./text-classifier-mcp/.env
    ports:
      - "8013:8000"
    volumes:
      - /home/nbrown:/workspace
